version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
      include: scope
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(actions)"
      include: scope
    labels:
      - dependencies
      - github-actions
